/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java
    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    maven {
        name = "rs"
        setUrl("https://www.rs.tu-darmstadt.de/artifactory/gradle-release")
    }
    jcenter()
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
}

val jacksonVersion = "2.9.9"
val jgraphtVersion = "1.3.1"
val slf4jVersion = "1.7.26"

dependencies {
    // Use JUnit Jupiter API for testing.
    implementation("org.slf4j:slf4j-api:$slf4jVersion")
    implementation("ch.qos.logback:logback-classic:1.2.3")

    implementation("org.logicng:logicng:1.5.1")

    implementation("org.jgrapht:jgrapht-io:$jgraphtVersion")
    implementation("org.jgrapht:jgrapht-core:$jgraphtVersion")

    implementation("org.apache.commons:commons-lang3:3.3.2")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("commons-cli:commons-cli:1.4")

    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-core:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion")

    implementation("com.github.dpaukov:combinatoricslib3:3.3.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5.5")
}

application {
    // Define the main class for the application
    mainClassName = "de.tu_darmstadt.rs.synbio.Main"
}

task("simulationTestbench", JavaExec::class) {
    main = "de.tu_darmstadt.rs.synbio.SimulationTestbench"
    classpath = sourceSets["main"].runtimeClasspath
}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}
